export const brands = JSON.parse(`
[
  "The Attico",
  "Moncler",
  "Paco Rabanne",
  "Jil Sander",
  "The Row",
  "Khaite",
  "Paris Texas",
  "Mach & Mach",
  "Acne Studios",
  "Alberta Ferretti",
  "Aldo Coppola",
  "Alessandra Rich",
  "Alexander McQueen",
  "Alexander Wang",
  "Alexandre Vauthier",
  "Ambush",
  "Amiri",
  "Armani Collezioni",
  "Baccarat",
  "Balenciaga",
  "Balmain",
  "Bell & Ross",
  "Bernardaud",
  "Billionaire Italian",
  "Bottega Veneta",
  "Brioni",
  "Brunello Cucinelli",
  "Burberry",
  "BVLGARI",
  "Canada Goose",
  "Casato",
  "Celine",
  "Chloé",
  "Chopard",
  "Christofle",
  "Corneliani",
  "Daum",
  "David Yurman",
  "de Bethune",
  "de Grisogono",
  "Dolce & Gabbana",
  "Dries Van Noten",
  "Dsquared2",
  "Emilio Pucci",
  "Ermanno Scervino",
  "Ermenegildo Zegna",
  "Couture",
  "F.P. Journe",
  "Fabergé",
  "Fendi",
  "Frette",
  "Garrard",
  "Gianvito Rossi",
  "Giorgio Armani",
  "Girard-Perregaux",
  "Givenchy",
  "Graff",
  "Grand Cru",
  "Greubel Forsey",
  "Gucci",
  "Harry Winston",
  "Hublot",
  "Il Gufo",
  "Isabel Marant",
  "Jacob & Co.",
  "Jenny Packham",
  "Jil Sander",
  "Judith Ripka",
  "JW Anderson",
  "Kids Village",
  "Kiton",
  "La Perla",
  "Lalique",
  "Lanvin",
  "Loewe",
  "Loro Piana",
  "Maison Margiela",
  "Marni",
  "MB&F",
  "Messika",
  "Mikimoto",
  "Mimi",
  "Moroni",
  "Nodaleto",
  "Off-White",
  "Oscar de la Renta",
  "Paco Rabanne",
  "Pasquale Bruni",
  "Patek Philippe",
  "Ralph Lauren",
  "Roberto Cavalli",
  "Rolex",
  "Rubeus Milano",
  "S.T. Dupont",
  "Saint Laurent",
  "Santoni",
  "Simonetta Ravizza",
  "Stella McCartney",
  "Stephen Webster",
  "Sutra",
  "The Attico",
  "The Row",
  "Tod's",
  "Tom Ford",
  "Totême",
  "Urwerk",
  "Utopia",
  "Valentino",
  "Vera Wang",
  "Versace",
  "Vetements",
  "Victoria Beckham",
  "Viktor & Rolf",
  "Yves Salomon",
  "Zenith",
  "Zilli",
  "Zimmermann",
  "Zuhair Murad"
]
`);
